"""PR creation — uses gh CLI when the repo has a remote, otherwise a local stub."""
import logging
import os
import subprocess
import tempfile
import uuid
from typing import Dict

logger = logging.getLogger("thin_slice.github_pr")


def create_pr_stub(repo_path: str, branch_name: str, changes: Dict[str, str]) -> str:
    """Create a PR branch and open a pull request.

    Tries the gh CLI path first; falls back to a local temp-dir stub.
    """
    unique = f"{branch_name}-{uuid.uuid4().hex[:8]}"
    if _gh_available() and _has_remote(repo_path):
        url = _gh_create_pr(repo_path, unique, changes)
        if url:
            return url
    return _local_stub(changes, unique)


# ── helpers ──────────────────────────────────────────────────────────────────

def _gh_available() -> bool:
    try:
        subprocess.run(["gh", "--version"], capture_output=True, check=True, timeout=5)
        return True
    except Exception:
        return False


def _has_remote(path: str) -> bool:
    try:
        result = subprocess.run(
            ["git", "-C", path, "remote"],
            capture_output=True, text=True, timeout=5,
        )
        return bool(result.stdout.strip())
    except Exception:
        return False


def _gh_create_pr(repo_path: str, branch: str, changes: Dict[str, str]) -> str | None:
    try:
        subprocess.run(
            ["git", "-C", repo_path, "checkout", "-b", branch],
            capture_output=True, check=True,
        )
        for rel, content in changes.items():
            abs_path = os.path.join(repo_path, rel)
            os.makedirs(os.path.dirname(abs_path), exist_ok=True)
            with open(abs_path, "w", encoding="utf-8") as fh:
                fh.write(content)
        subprocess.run(["git", "-C", repo_path, "add", "."], capture_output=True, check=True)
        subprocess.run(
            ["git", "-C", repo_path, "commit", "-m", "thin-slice: automated code generation"],
            capture_output=True, check=True,
        )
        subprocess.run(
            ["git", "-C", repo_path, "push", "-u", "origin", branch],
            capture_output=True, check=True,
        )
        result = subprocess.run(
            [
                "gh", "pr", "create",
                "--title", "Thin-Slice: automated code generation",
                "--body", f"Generated by Thin-Slice.\n\nFiles changed:\n" + "\n".join(f"- `{k}`" for k in changes),
                "--head", branch,
                "--base", "main",
            ],
            capture_output=True, text=True, check=True, cwd=repo_path,
        )
        url = result.stdout.strip()
        logger.info("PR created: %s", url)
        return url
    except Exception as exc:
        logger.warning("gh PR creation failed: %s", exc)
        try:
            subprocess.run(["git", "-C", repo_path, "checkout", "-"], capture_output=True)
        except Exception:
            pass
        return None


def _local_stub(changes: Dict[str, str], pr_id: str) -> str:
    tmp = tempfile.mkdtemp(prefix="pr_stub_")
    for path, content in changes.items():
        full = os.path.join(tmp, path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as fh:
            fh.write(content)
    logger.info("PR stub written to %s (set GITHUB_TOKEN + remote to get a real PR)", tmp)
    return f"local://thin-slice/pull/{pr_id}"
